<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="StackExchange.Redis" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TicketNest.Application.Events\TicketNest.Application.Events.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="TicketNest.Events.Tests" />
        <InternalsVisibleTo Include="TicketNest.Events.IntegrationTests" />
    </ItemGroup>

</Project>
