<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TicketNest.Domain.Auth\TicketNest.Domain.Auth.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>      <InternalsVisibleTo Include="TicketNest.Auth.Tests" />
      <InternalsVisibleTo Include="TicketNest.Events.Tests" />
      <InternalsVisibleTo Include="TicketNest.Bookings.Tests" />
      <InternalsVisibleTo Include="TicketNest.Shared.Tests" />
      <InternalsVisibleTo Include="TicketNest.Events.IntegrationTests" />
      <InternalsVisibleTo Include="TicketNest.Kafka.IntegrationTests" />
    </ItemGroup>

</Project>
