<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Abstractions"/>
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="Swashbuckle.AspNetCore"/>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\TicketNest.Application.Bookings\TicketNest.Application.Bookings.csproj" />
      <ProjectReference Include="..\TicketNest.DataAccess.Bookings\TicketNest.DataAccess.Bookings.csproj" />
      <ProjectReference Include="..\TicketNest.Queues\TicketNest.Queues.csproj" />
    </ItemGroup>

</Project>
